# Generated by Django 4.2.18 on 2025-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerrequest_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerrequest',
            options={'permissions': [('can_view_requests', 'Can view support requests'), ('can_change_status', 'Can change request status')]},
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='request_type',
            field=models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('billing', 'Billing'), ('servicing', 'Servicing'), ('other', 'Other')], max_length=20),
        ),
    ]
